# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 10
      uses: actions/setup-node@v3
      with:
        node-version: '12'

    - name: Run Cypress
      run: |
        npm ci
        npm run cypress
      env:
        CI: true

    - name: Upload artifact Web automation
      uses: actions/upload-artifact@master
      with:
        name: webAutomation.cy.js.mp4
        path: /home/runner/work/cypress/videos/webAutomation.cy.js.mp4

    - name: Upload artifact API automation
      uses: actions/upload-artifact@master
      with:
        name: apiAutomation.cy.js.mp4
        path: /home/runner/work/cypress/videos/apiAutomation.cy.js.mp4
